### ISSUE TITLE
信息界面点进去图片是有transition动画效果的，但是

### ISSUE THREAD

**Issue by MewX** [yueeng/hacg#1]
`左上角的返回按钮`点过之后和`返回实体按钮`点过之后效果不一样，实体按钮有transition动画，左上角返回按钮没有，需要处理下~

做的不错的说！

**Comment by MewX** [comment]
再补一个BUG，信息界面如果有音乐，点开音乐之后返回，音乐还在继续 \_(:3」∠)\_

**Comment by yueeng** [comment]
谢谢反馈。
1、左上角返回按钮原意是想无论在那个界面都可直接返回主界面，不过看来用处不大，已调整为的物理键返回功能相同。
2、音乐在不停止问题已修正。
