### ISSUE TITLE
130出现闪退

### ISSUE THREAD

**Issue by lvzhenbo** [yueeng/hacg#14]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/polaris/polaris:9/PKQ1.180729.001/9.9.26:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 13058, tid: 13153, name: ThreadPoolForeg  >>> io.github.yueeng.hacg <<<
signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x787644a938
Abort message: '[FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
'
    x0  0000000000000000  x1  0000000000000081  x2  000000007fffffff  x3  0000000000000000
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  7f7f7f7f7fff7f7f
    x8  0000000000000000  x9  0000000000000000  x10 0000000000000001  x11 0000000000000000
    x12 000000786b30ae00  x13 ffffffffffffffff  x14 ffffffffff000000  x15 ffffffffffffffff
    x16 000000790dc73230  x17 000000790dba2f10  x18 0000000000000001  x19 000000786ba75a70
    x20 000000786ba75a78  x21 000000786ba75a80  x22 000000000000004f  x23 000000790dc753c0
    x24 00000078785f8000  x25 000000786ba76588  x26 000000786a8cc2a0  x27 000000786ba76588
    x28 0000000000000000  x29 000000786ba75a60
    sp  000000786ba755b0  lr  000000787644a7f8  pc  000000787644a938

backtrace:
    #00 pc 000000000201c938  /data/app/com.google.android.webview-C5cnL-BJEebkrMuh6iK0Ow==/lib/arm64/libwebviewchromium.so

**Comment by yueeng** [comment]
这个问题应该已经好了，如果有问题请再次留言。

**Comment by lvzhenbo** [comment]
希望能够适配全面屏

**Comment by yueeng** [comment]
> 希望能够适配全面屏

已更新
