### ISSUE TITLE
‘’前作‘’、‘’上集‘’文字的链接无法在应用内跳转，请求修复，谢谢

### ISSUE THREAD

**Issue by Mingtu2019** [yueeng/hacg#19]
‘’前作‘’、‘’上集‘’文字的链接无法在应用内跳转，请求修复，谢谢！

**Comment by yueeng** [comment]
[v1.5.1](/yueeng/hacg/releases/tag/1.5.1) 应用内跳转已增加。

**Comment by Mingtu2019** [comment]
报告，又不能跳转了！谢谢！
