### ISSUE TITLE
大佬欢迎来到琉璃神社官方群来。

### ISSUE THREAD

**Issue by filusilia** [yueeng/hacg#3]

**Comment by yueeng** [comment]
群号多少啊？

**Comment by filusilia** [comment]
你留下你号  我拉你。。 群没开放加入

**Comment by yueeng** [comment]
群号发我邮箱：ssiori@gmail.com

**Comment by yueeng** [comment]
我发邮件到 filus520@gmail.com 邮箱了。

**Comment by Arrow-C** [comment]
群号呢？

**Comment by filusilia** [comment]
你可以发给我邮箱... 上面的大佬拉了没反应 嗨呀=,=

**Comment by yueeng** [comment]
我发邮件到 filus520@gmail.com 邮箱了，又发了一次。

**Comment by perfectrogge** [comment]
请务必拉我 T_T 954455177

**Comment by Rayark-VOEZ** [comment]
1512979396求把我拉进群

**Comment by qqwj12** [comment]
是QQ群？拉我进群。。304371256

**Comment by mzw123456789** [comment]
拉我入群里，2416878948
现在APP刷新不出贴子了，怎么办？

**Comment by Eternity127** [comment]
2793867662
大佬一定要拉我入群啊(ง •̀_•́)ง

**Comment by rangolam** [comment]
拉我进群337669685@qq.com

**Comment by rangolam** [comment]
麻烦拉我进群337669685

**Comment by GoogleJ** [comment]
原生系统的虚拟按键栏会遮挡内容部分.还说想重构一下,,,看不懂...

**Comment by yueeng** [comment]
@GoogleJ 这个问题在1.2.3版已经修复。

**Comment by Moreki** [comment]
电报群吗？拜托啦～moreki@live.jp

**Comment by aaaol** [comment]
大佬我要进群 786084665

**Comment by zhumengle** [comment]
大佬我要进群 734421679

**Comment by Eternity127** [comment]
大佬，铁杆粉丝啊。一定要拉我进群2793867662@qq.com

**Comment by renshengaaa** [comment]
拉我    1804445877@qq.com

**Comment by CANYUEHUAYU** [comment]
求给我tg群号805730257@qq.com

**Comment by Moreki** [comment]
上面留了邮箱可是没有收到

**Comment by UltramanTIGA** [comment]
兄弟，最近网站挂了吗，还是又换了什么域名
