### ISSUE TITLE
向下滑至底部，无法翻页

### ISSUE THREAD

**Issue by Mingtu2019** [yueeng/hacg#59]
向下滑至底部无法继续下滑转到第二页，显示“没有更多了”，谢谢
如图
![Screenshot_20211113_170635](https://user-images.githubusercontent.com/49590221/141613067-d04f6de5-43e4-445e-afe0-8538ae3a6d77.jpg)

**Comment by Mingtu2019** [comment]
> 向下滑至底部无法继续下滑转到第二页，显示“没有更多了”，谢谢 如图 ![Screenshot_20211113_170635](https://user-images.githubusercontent.com/49590221/141613067-d04f6de5-43e4-445e-afe0-8538ae3a6d77.jpg)

更换域名也无法解决，科学上网也不行

**Comment by yueeng** [comment]
[v1.5.4](/yueeng/hacg/releases) 已修正。
