### ISSUE TITLE
怎么把假冒网站的域名加进去了

### ISSUE THREAD

**Issue by sdbds** [yueeng/hacg#7]
真域名是https://www.llss.fun/wp/
dog系列都是不要脸的爬虫，还开淘宝和广告。
我不知道作者是故意的还是不知道。

**Comment by yueeng** [comment]
配置文件已改，关于dog域名还真不知道，这个应用是抓页面，有广告代码也基本不会展示。

**Comment by yueeng** [comment]
已更新1.2.6，修正这个真假域名问题.

**Comment by sdbds** [comment]
感谢作者，我以为三方APP的作者和假站是一个人开的所以语气有点冲抱歉。
假站一直靠爬虫偷数据和淘宝广告盈利，而且一直以来使用三方APP做宣传，并且自称是该APP作者。打开假站APP下载页面我看到：因为本人对制作APP不熟悉，可能有很多不如意的地方，敬请谅解；

所以造成误解请谅解。另外ch和love域名也是假站的，希望作者不要被当枪使，做出来的app被人拿来盈利。

**Comment by yueeng** [comment]
我写这个APP也是学习和自用，由于APP我自己使用频率不高，所以发现域名不能用时，就去百度上搜一下，看到能用的域名就写上去了，也没关注到真假域名问题。
**我本人决决对对和假网站没有任何关系。。。**

**Comment by zhz1237ok** [comment]
琉璃神社只要加一行hacg.me就行了，自动会跳转到最新域名
