### ISSUE TITLE
全面屏未适配

### ISSUE THREAD

**Issue by ghost** [yueeng/hacg#8]
在二级目录低部会显示一级目录

**Comment by yueeng** [comment]
没有全面屏手机，能截个图吗？

**Comment by AmahaSuzune** [comment]
![screenshot_20181009-192523_hacg](https://user-images.githubusercontent.com/34571475/46666933-a7aa0480-cbfa-11e8-81e7-9f7941a54952.jpg)
da'f大概是这样吧。。。仔细看最底下 我是三星S9+

**Comment by AMNOTSR** [comment]
同上↑↑mix3

**Comment by yueeng** [comment]
已更新
